### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by dpo** [comment]
Error on Windows:
```
conversion Float64: Error During Test at C:\projects\quadmath-jl\test\runtests.jl:5
  Test threw exception ErrorException("error compiling Type: could not load library \"libgcc_s_seh-1.dll\"\nThe specified module could not be found.\r\n")
  Expression: Float128(T(1)) + Float128(T(2)) == Float128(T(3))
  error compiling Type: could not load library "libgcc_s_seh-1.dll"
  The specified module could not be found.
```

**Comment by simonbyrne** [comment]
@dpo Yes, this is a known issue. See #16.

**Comment by simonbyrne** [comment]
I think we can just remove the section on installation altogether, since installing via the package manager is the default.

**Comment by simonbyrne** [comment]
Updated in 2bb517575ba3cf042ad00a99afb0e39f461251ff

**Pull request closed without merging**
